### ISSUE TITLE
Customer Portal / Invoices

### ISSUE THREAD

**Issue by NDMO** [bezlio/bezlio-recipes#3]
Create a Bezl that will allow a customer to easily pull up their invoices. The primary listing will be 'Open Invoices' and we will display some quick summary information including the invoice total and due date. If the invoice it past due, a warning badge should be presented next to it indicating as much. An invoice search widget should follow allowing the user to search by invoice number, part, invoice date range. Each invoice should also include a download button visible if the file system plugin sees a file in the directory matching the invoice number. This project should first be written targeting Excel with ODBC and committed to 'master'. The it shoud be ported to Epicor10, Epicor905, and Visual70.

**Comment by ahodakovskaya** [comment]
Is there a good example of an existing recipe I can compare to, one that was written for Excel with ODBC and then ported to either Epicor or Visual?  I have a lot of questions about the above and maybe looking at a similar recipe implementation can help me understand the structure of these.
Or maybe e-mail another recipe Bezl that I can import and look over.

Or, questions to  help me start:
1.  Target Excel with ODBC:  Am I targeting a generic Excel file, and making it whatever format I want in order to create an example of how the Bezl will look with some data loaded?  Do I need to support a dynamic format of any Excel file defined by user?
2.  For download button, it sounds like I would need to create a FileSystem data subscription that accepts a single FileName.  Are any Bezlio training videos available yet by chance?  I would have to manually create a data subscription for this one (not through the Data Subscription editor) and my memory needs refreshed. (Unless such a data connection is included in the Bezl available for import above).
3.  For searching through invoices:  Is this only for invoice data that has been pulled back from server and is now shown on screen, or does this search need to hit the server?

**Comment by aellis** [comment]
@ahodakovskaya, I am actually reworking the recipe book at the moment in a way that I think will help you out a ton with this one.  Let's schedule some time for a TurboMeeting early next week so I can give you a tour and help you get started here.  Just shoot me an invite for when we are both open.

**Comment by aellis** [comment]
Closing this out in support of the new focus purely on sales roles initially.  This will be re-opened when focus will be moved to this role.
